// contracts/index.ts — 契约层统一出口
// 实现层（engine/infra/operations）只允许从这里 import 类型，
// 禁止跨契约文件互相深引用（由 lint 规则约束）。

export * from './base'
export * from './transaction'
export * from './lock'
export * from './paths'
export * from './validation'
export * from './hooks'
export * from './scoring'
export * from './scan'
export * from './health.contract'
export * from './logging'
export * from './doctor.contract'
export * from './dedup.contract'
export * from './restore-point.contract'
export * from './blast-radius.contract'
export * from './trend.contract'
export * from './policy.contract'
export * from './disk-forecast.contract'
export * from './guardian.contract'
export * from './ledger.contract'
